### ISSUE TITLE
Ignition finish trail time cause designer to freeze

### ISSUE THREAD

**Issue by NaderChinichian** [Kyvis-Labs/ignition-apexcharts-module#30]
When the trial version finish if I open a view that include APEX chart with history binding for data, the view is getting very slow and freeze.

**Comment by nikolai-wolterstorff** [comment]
I take it history binding means tag history? If your tag history module is on an expired trial you cannot pull tag history with a binding. You can see this happen along with a warning message on the Power Chart component.

**Comment by traviscox** [comment]
If you remove the tag history bindings, does it still get slow?

**Comment by NaderChinichian** [comment]
Hi Travis,
No, it gets working again if remove the binding. 
In this case, I just got and reset the trial, and after 5sec the designer back to normal.
For binding, after History Bind I use simple Script Transform to change the format of the return list that matches Apex Data format.(No fancy things)

**Comment by traviscox** [comment]
I think I fixed this issue in 1.0.10. You will also no longer have to use a script transform. The module will take care of that for you, i.e. the first column is x and the second column is y. Can you check out this version:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.10](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.10)

**Comment by traviscox** [comment]
Had to fix another small issue, now at 1.0.11:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.11](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.11)

**Comment by NaderChinichian** [comment]
Hi Travis,
I test 1.0.11 with 8.1.23 and still have the same problem after the trial version of Igntion is pass the designer freeze.
By the way this time I delete my script transform and use directly history binding which is working but the trail problem remain

**Comment by traviscox** [comment]
Closed due to inactivity
